# Generated by Django 5.0.2 on 2024-04-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='ФИО')),
                ('post', models.CharField(max_length=128, verbose_name='Должнсть')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('director', models.BooleanField(verbose_name='Руководитель')),
                ('doctor', models.BooleanField(verbose_name='Врач')),
                ('teacher', models.BooleanField(verbose_name='Педагог')),
            ],
        ),
    ]
