# Generated by Django 5.0.2 on 2024-04-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='post_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='Должнсть'),
        ),
        migrations.AddField(
            model_name='people',
            name='post_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Должнсть'),
        ),
        migrations.AlterField(
            model_name='people',
            name='image',
            field=models.ImageField(upload_to='people/', verbose_name='Фото'),
        ),
    ]
